### ISSUE TITLE
Failed to assign to property 'Opportunity.UWP.Controls.DataTemplateKeyValuePair.Key'. [Line: 0 Position: 0]"

### ISSUE THREAD

**Issue by Copay** [OpportunityLiu/ExViewer#88]
![image](https://user-images.githubusercontent.com/11085755/44030071-325a67fa-9f32-11e8-9083-52bf092c1547.png)

AppLog:
```
[2018-08-13 11:48:48Z]
--------Exception Info--------
Type: Windows.UI.Xaml.Markup.XamlParseException
HResult: 0x802B000A
HelpLink: 
Message: @"The text associated with this error code could not be found.

Failed to assign to property 'Opportunity.UWP.Controls.DataTemplateKeyValuePair.Key'. [Line: 0 Position: 0]"
DisplayedMessage: @"Failed to assign to property 'Opportunity.UWP.Controls.DataTemplateKeyValuePair.Key'. [Line: 0 Position: 0]"
Source: <unknown>
Data:
  [RestrictedDescription]: Type=System.String, ToString=@"Failed to assign to property 'Opportunity.UWP.Controls.DataTemplateKeyValuePair.Key'. [Line: 0 Position: 0]"
  [RestrictedErrorReference]: null
  [RestrictedCapabilitySid]: null
  [__RestrictedErrorObject]: Type=EETypeRva:0x0003c7e8, ToString=@"EETypeRva:0x0003c7e8"
StackTrace:
     at SharedLibrary!<BaseAddress>+0x4a0ad0
     at ExViewer!<BaseAddress>+0x17cbdc5
     at ExViewer!<BaseAddress>+0x1c6ca7b
     at Opportunity.MvvmUniverse.Services.Navigation.FrameWrapper.NavigateAsync(Type sourcePageType, Object parameter)
     at ExViewer!<BaseAddress>+0x1890fa3
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at SharedLibrary!<BaseAddress>+0x4d5ce0
     at SharedLibrary!<BaseAddress>+0x4d5c68
     at SharedLibrary!<BaseAddress>+0x4d5c27
     at SharedLibrary!<BaseAddress>+0x50931f
     at ExViewer!<BaseAddress>+0x203fd81
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at SharedLibrary!<BaseAddress>+0x65496e
     at SharedLibrary!<BaseAddress>+0x4f5158
     at SharedLibrary!<BaseAddress>+0x4f54bc
     at SharedLibrary!<BaseAddress>+0x4a0ad0
     at ExViewer!<BaseAddress>+0x188d3a8
     at ExViewer!<BaseAddress>+0x188d2e4
     at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.<.ctor>b__17_1(Object sender, ApplicationModel.Core.UnhandledErrorDetectedEventArgs eventArgs)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.<.ctor>b__17_1(Object sender, ApplicationModel.Core.UnhandledErrorDetectedEventArgs eventArgs)
     at System.EventHandler<System.Threading.Tasks.UnobservedTaskExceptionEventArgs>.Invoke(Object sender, Threading.Tasks.UnobservedTaskExceptionEventArgs e)
     at ExViewer!<BaseAddress>+0x1a09426
     at ExViewer!<BaseAddress>+0x1a09b1f
Inner Exception: null
--------Other Info--------
Package: 2289Opportunity.E-Viewer_2018.8.13.0_x64__x517s75edqf2e @ bb424fee9267474f3c7caa785c55ef6f30afe748
FrameStack:
  >>  <<


```

PackageInfo:
```

PackageFullName: 2289Opportunity.E-Viewer_2018.8.13.0_x64__x517s75edqf2e
PackageVersion: 2018.8.13.0
PackageArchitecture: X64
PackageNeedsRemediation: False
GithubBranch: master
GithubCommit: bb424fee9267474f3c7caa785c55ef6f30afe748
```

DeviceInfo:

```
Qualifiers: Language=en-US;zh-Hans-CN, Contrast=standard, Scale=125, HomeRegion=GB, TargetSize=, LayoutDirection=LTR, Theme=light, AlternateForm=, DXFeatureLevel=, Configuration=, DeviceFamily=Desktop, Custom=, 
DeviceForm: Unknown
DeviceFamily: Windows.Desktop
DeviceFamilyVersion: 10.0.18214.1000
DeviceId: ac33839b-188e-6328-9531-fef56cfd2277
OperatingSystem: WINDOWS
SystemFirmwareVersion: 
SystemHardwareVersion: 
SystemManufacturer: System manufacturer
SystemProductName: System Product Name
SystemSku: SKU
```

**Comment by OpportunityLiu** [comment]
确实有问题，发布包先删除了
